language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t francisgu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true francisgu/docker-react npm run test
